from setuptools import setup, find_packages

setup(
    name='ponoki',
    version='1.0.0',
    packages=find_packages(),
    description='A Python-based password security tool',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/CraigOpie/ponoki',
    author='Craig Opie',
    author_email='craigopie@gmail.com',
    license='Creative Commons Zero v1.0 Universal',
    install_requires=[
        'requests',
    ],
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Topic :: Security",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: OS Independent",
        "Natural Language :: English",
    ],
)